name: "AWS Review and deploy"
run-name: ${{ github.actor}} is running a Terraform review and deploy to AWS 🚀
on:
  push:
    branches:
      - aws-main
  pull_request:
    branches:
      - aws-main

permissions:
  # id-token write required for OIDC, contents read required for actions/checkout, pull-requests write required to comment on PR
  id-token: write
  contents: read
  pull-requests: write

env:
   TF_LOG: INFO
   AWS_REGION: ${{ vars.TF_VAR_REGION }}
   AWS_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET_NAME }}
   AWS_BUCKET_KEY_NAME: ${{ secrets.TF_STATE_BUCKET_KEY }}

jobs:
 terraform:
   name: "Terraform Infrastructure Change Management"
   runs-on: ubuntu-latest
   steps:
    - name: Checkout the repository to the runner
      uses: actions/checkout@v4
    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.1
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -no-color
      continue-on-error: false